services:
  db:
    image: postgres:17.2
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data: