version: "3.9"

services:
  db:
    image: postgres:17.2
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - app-net

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:

volumes:
  static_volume:
  media_volume: