services:
  db:
    image: postgres:17.2
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media/
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - "8000"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - media_volume:/media

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend


volumes:
  postgres_data:
  static_volume:
  media_volume: