# Generated by Django 5.2 on 2025-04-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeprice',
            name='last_day_fixation',
            field=models.DateField(default=None, null=True),
        ),
    ]
