# Generated by Django 5.2 on 2025-04-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_coffeeprice_last_day_fixation'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeprice',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
